[package]
name = "git-public-keys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.4"
git2 = "0.18.1"
log = "0.4.20"
tempdir = "0.3.7"
